# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Bootcamp Machine Learning
email: benebenebene007@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Halaman ini berisi tentang hasil analisis data yang saya lakukan terhadap dataset FIFA 19. Sebagai penggemar sepakbola,
  tentu menjadi suatu kesenangan tersendiri untuk bisa melakukan analisis terhadap data-data dari game FIFA 19. Selain
  melakukan analisis, saya pun membuat model Machine Learning untuk memprediksi Overall dari pesepakbola di FIFA 19 berdasarkan
  feature-feature yang terdapat pada dataset FIFA 19 ini
baseurl: "" # the subpath of your site, e.g. /blog
url: ""
permalink: /:year/:month/:day/:title/
twitter_username: benedict_bayu
github_username:  benedictbayu

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
